api = "0.10"

[buildpack]
id = "heroku/website-nodejs"
version = "1.0.8"
name = "Heroku Website/Node.js"
description = "Heroku's buildpack for static web apps that require Node.js for build."
keywords = ["ember", "emberjs", "heroku"]

[[buildpack.licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "heroku/nodejs"
version = "5.0.0"

[[order.group]]
id = "heroku/static-web-server"
version = "1.0.8"

[[order.group]]
id = "heroku/website-ember"
version = "1.0.8"

[[metadata.targets]]
os = "linux"
arch = "amd64"

[[metadata.targets]]
os = "linux"
arch = "arm64"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-website-nodejs" }
