api = "0.10"

[buildpack]
id = "heroku/website-public-html"
version = "2.2.0"
name = "Heroku Website (Public HTML)"
description = "Basic website support for heroku/buildpacks-frontend-web."

[[buildpack.licenses]]
type = "MIT"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-website-public-html" }
