api = "0.10"

[buildpack]
id = "heroku/website-ember"
version = "3.0.0"
name = "Heroku Website (Ember.js)"
description = "Ember.js support for heroku/buildpacks-frontend-web."

[[buildpack.licenses]]
type = "MIT"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-website-ember" }
